# Neural Network

In [4]:
import numpy as np
import math

## Sigmoid Function

In [5]:
def sigmoid(x):
    y = [1 / (1 + math.pow(math.e, -(i))) for i in x]
    return y

## Neural Network 2 layers

In [6]:
inputData = np.array([1.0, 0.5])
W11 = 0.9
W12 = 0.2
W21 = 0.3
W22 = 0.8

X1 = (inputData[0] * W11) + (inputData[1] * W21)
X2 = (inputData[0] * W12) + (inputData[1] * W22)
X1 = [X1]
X2 = [X2]
y1 = sigmoid(X1)
y2 = sigmoid(X2)

outputData = np.array([y1, y2]).reshape(2)

# print(y1)
# print(y2)
# Input Data 
print("INPUT DATA: ")
print(inputData)
print("\n")
print("OUTPUT DATA: ")
print(outputData)

INPUT DATA: 
[1.  0.5]


OUTPUT DATA: 
[0.7407749  0.64565631]


## Neural Network Multiple Layer

In [15]:
data = np.array([0.9, 0.1, 0.8])
W_input_hidden_layer = [0.9, 0.3, 0.4, 0.2, 0.8, 0.2, 0.1, 0.5, 0.6]
W_input_hidden_layer = np.array(W_input_hidden_layer).reshape(3,3)

W11 = 0.9
W22 = 0.8
W31 = 0.1
W33 = 0.9

W_hidden_output = np.array([0.3, 0.7, 0.5, 0.6, 0.5, 0.2, 0.8, 0.1, 0.9]).reshape(3,3)


X_hidden = np.dot(W_input_hidden_layer, data)

Output_hidden = sigmoid(X_hidden)

X_output = np.dot(W_hidden_output, Output_hidden)

O_output = sigmoid(X_output)

print("Input: ")
print(data)
print()
print("Hidden Layer 1: ")
print(X_hidden)
print()
print("Hidden layer2: ")
print(Output_hidden)
print()
print("Hidden layer3: ")
print(X_output)
print()
print("Output: ")
print(O_output)

Input: 
[0.9 0.1 0.8]

Hidden Layer 1: 
[1.16 0.42 0.62]

Hidden layer2: 
[0.7613327148429104, 0.6034832498647263, 0.6502185485738271]

Hidden layer3: 
[0.97594736 0.88858496 1.25461119]

Output: 
[0.7263033450139793, 0.7085980724248232, 0.778097059561142]
